#!/usr/bin/env node
"use strict";

var fs = require('fs'),
	when = require('when'),
	sequence = require('sequence'),
	app = require('express')(),
	server = require('http').createServer(app),
	io = require('socket.io').listen(server),
	leveldb = require('leveldb');

var users = {};

console.log('starting server');

sequence().then(function(next){

	leveldb.open(__dirname + "/messages.db", {create_if_missing: true}, function(err, db){
		console.log('database connected');
		next(db);
	});

}).then(function(next, db){

	server.listen(8080);

	// data routes
	io.sockets.on('connection', function(socket){
		socket.on('login', function(data){
			// associate socket ID with user
			// return a list of chats with their chat IDs
		});
		socket.on('getChat', function(data){
			// return messages
			//
		});
		socket.on('newMessage', function(data){

		});
	});

	// app route
	app.get('/', function (req, res) {
		res.file(__dirname + '/views/index.html');
	});

	// admin route
	app.get('/admin', function (req, res) {
		res.file(__dirname + '/views/admin.html');
	});

});

